---

- name: NGINX | Installing NGINX
  apt: 
    name: "{{ nginx_package }}"
    state: present
    update_cache: yes

- name: Copy default nginx config
  template:
    src: nginx.conf.j2
    dest: "{{ nginx_conf_file_path }}"
    owner: root
    group: root
    mode: 0644
  notify:
    - restart nginx

- name: OPENSSL | Update Openssl
  apt:
    name: "{{ item }}"
    state: latest
    only_upgrade: yes
    update_cache: yes
  with_items:
    - libssl1.0.0
    - openssl
  notify: restart nginx